version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/devops-training
hooks: 
  ApplicationStop: 
    - location: stop_container.sh
      runas: root
      timeout: 10000
  ApplicationStart: 
    - location: start_container.sh
      runas: root
      timeout: 10000 
  ValidateService: 
    - location: validate_service.sh
      runas: root
      timeout: 10000 